spring:
  messages:
    basename: "i18n/messages"
    encoding: "UTF-8"
application:
  path: questions_en.csv
  locale: en
  requestUserData: request.user.data
  passedMessage: template.passed
  failedMessage: template.failed
  passingScore: 3