server:
  port: 8762
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
#      routes:
#        - id: library
#          uri:  lb://library-service
#          predicates:
#            - Path=/api/**
      filter:
        secure-headers:
          disable: x-frame-options, strict-transport-security
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  eureka:
    client:
      registerWithEureka: false
      fetchRegistry: false
      service-url:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

