spring:
  data:
    mongodb:
      host: localhost
      database: library
      port: 27017

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.hw8.mongock.changelog