server:
  port: 8080
spring:
  application:
    name: library-service
  eureka:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      register-with-eureca: true
      fetch-registry: true
    instance:
      preferIpAddress: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
  jmx:
    enabled: true

resilience4j.circuitbreaker:
  metrics:
    enabled: true
  configs:
    default:
      slidingWindowType: COUNT_BASED
      failureRateThreshold: 5
      slowCallRateThreshold: 10
      slowCallDurationThreshold: 60000
      registerHealthIndicator: true
      allowHealthIndicatorToFail: true
      minimumNumberOfCalls: 10
      slidingWindowSize: 3
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 3000
  instances:
    authorServiceCircuitBreaker:
      base-config: default
    bookServiceCircuitBreaker:
      baseConfig: default
    commentServiceCircuitBreaker:
      base-config: default
    genreServiceCircuitBreaker:
      base-config: default

management:
  endpoints:
    web:
      exposure:
        include: metrics, health, logfile
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  file:
    name: hw18.log